name: habilita_enem
description: Aplicativo para treinar para o Enem.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  typed_data: ^1.3.1
  json_annotation: ^4.6.0
  dio: ^4.0.6
  equatable: ^2.0.5
  rxdart: ^0.27.5
  firebase_auth: ^3.8.0
  firebase_core: ^1.22.0
  get_it: ^7.2.0
  flutter_bloc: ^8.1.1
  formz: ^0.4.1
  cloud_firestore: ^3.4.7
  firebase_storage: ^10.3.8
  flutter_neumorphic: ^3.2.0
  shared_preferences: ^2.0.15
  image_picker: ^0.8.5+3
  modal_bottom_sheet: ^2.1.2
  # camera: 0.9.4+5
  # auto_size_text: ^3.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
